import io
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas


def generate_acceptance_pack_pdf(
    lead_name: str,
    program: str,
    letter_body: str,
    campus: str = "AdmitOS University",
) -> bytes:
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    c.setFont("Helvetica-Bold", 22)
    c.drawString(72, height - 72, campus)
    c.setFont("Helvetica", 12)
    c.drawString(72, height - 95, "Office of Admissions")
    c.drawString(72, height - 112, datetime.utcnow().strftime("%B %d, %Y"))

    c.setFont("Helvetica-Bold", 14)
    c.drawString(72, height - 150, f"Acceptance Pack — {lead_name}")

    c.setFont("Helvetica", 11)
    y = height - 180
    for line in _wrap(letter_body, 85):
        c.drawString(72, y, line)
        y -= 14
        if y < 120:
            c.showPage()
            y = height - 72

    y -= 20
    c.setFont("Helvetica-Bold", 11)
    c.drawString(72, y, "Enclosed Documents:")
    y -= 16
    c.setFont("Helvetica", 10)
    for doc in [
        "1. Official Acceptance Letter",
        "2. Enrollment Checklist",
        "3. Fee Schedule & Payment Instructions",
        "4. Housing Application Form",
        "5. International Student Visa Guide",
    ]:
        c.drawString(90, y, doc)
        y -= 14

    c.setFont("Helvetica-Oblique", 9)
    c.drawString(72, 60, f"Program: {program} | Generated by AdmitOS")

    c.save()
    buffer.seek(0)
    return buffer.read()


def _wrap(text: str, width: int) -> list[str]:
    words = text.replace("\n", " ").split()
    lines, current = [], ""
    for w in words:
        if len(current) + len(w) + 1 <= width:
            current = f"{current} {w}".strip()
        else:
            if current:
                lines.append(current)
            current = w
    if current:
        lines.append(current)
    return lines or [""]
